application: music-app-frontend-test1    #.appspot.com
version: 1
runtime: python27
api_version: 1
threadsafe: yes



skip_files:
- ^(.*/)?app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.less
- ^/docs*
- ^(.*/)?.node_modules\.*
- ^node_modules


handlers:


- url: /assets/(img|data|css|js|partials)/(.*)
  static_files: assets/\1/\2
  upload: assets/(img|data|css|js|partials)/(.*)

- url: /app/(controllers|directives|services|views)/(.*)
  static_files: app/\1/\2
  upload: app/(controllers|directives|services|views)/(.*)

- url: /app/(.*)
  static_files: app/\1
  upload: app/(.*)

- url: /deploy/(.*)
  static_files: deploy/\1
  upload: deploy/(.*) 

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
